import { Engine } from './marquinhos-engine.js';

export class MarquinhosUI {
    constructor() {
            this.config = Engine.obtenerConfigVisual();
                    this.expandido = false;
                            this.init();
                                }

                                    init() {
                                            document.documentElement.style.setProperty('--m-primary', this.config.theme.primary);
                                                    document.documentElement.style.setProperty('--m-blur', this.config.theme.blur);
                                                            document.documentElement.style.setProperty('--m-width', this.config.ui.width);
                                                                    document.documentElement.style.setProperty('--m-height', this.config.ui.height);
                                                                            document.documentElement.style.setProperty('--m-glass', this.config.theme.glass);

                                                                                    const container = document.createElement('div');
                                                                                            container.id = 'marquinhos-container';
                                                                                                    container.innerHTML = `
                                                                                                                <div class="m-burbuja"></div>
                                                                                                                            <div class="m-ventana">
                                                                                                                                            <div class="m-mensajes"></div>
                                                                                                                                                            <div class="m-input-area">
                                                                                                                                                                                <input type="text" class="m-input" placeholder="Escribe un mensaje...">
                                                                                                                                                                                                    <button class="m-btn-enviar">Enviar</button>
                                                                                                                                                                                                                    </div>
                                                                                                                                                                                                                                    <button class="m-btn-horario">Ver horario</button>
                                                                                                                                                                                                                                                </div>
                                                                                                                                                                                                                                                        `;
                                                                                                                                                                                                                                                                document.body.appendChild(container);

                                                                                                                                                                                                                                                                        const style = document.createElement('style');
                                                                                                                                                                                                                                                                                style.textContent = `
                                                                                                                                                                                                                                                                                            #marquinhos-container { position: fixed; bottom: 20px; right: 20px; z-index: 9999; transition: transform 0.3s; }
                                                                                                                                                                                                                                                                                                        .m-burbuja { width: 60px; height: 60px; border-radius: 50%; background: var(--m-primary); 
                                                                                                                                                                                                                                                                                                                                 cursor: pointer; backdrop-filter: blur(var(--m-blur)); border: 1px solid rgba(255,255,255,0.2); 
                                                                                                                                                                                                                                                                                                                                                          box-shadow: 0 4px 15px rgba(0,0,0,0.2); }
                                                                                                                                                                                                                                                                                                                                                                      .m-ventana { display: none; width: var(--m-width); height: var(--m-height); background: var(--m-glass); 
                                                                                                                                                                                                                                                                                                                                                                                               backdrop-filter: blur(var(--m-blur)); border-radius: 20px; border: 1px solid rgba(255,255,255,0.2); 
                                                                                                                                                                                                                                                                                                                                                                                                                        flex-direction: column; overflow: hidden; padding: 15px; }
                                                                                                                                                                                                                                                                                                                                                                                                                                    .m-mensajes { flex: 1; overflow-y: auto; margin-bottom: 10px; }
                                                                                                                                                                                                                                                                                                                                                                                                                                                .m-no-leido { color: #faedcd; font-weight: bold; margin: 4px 0; }
                                                                                                                                                                                                                                                                                                                                                                                                                                                            .m-leido { color: #d4a373; opacity: 0.6; margin: 4px 0; }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                        .m-input-area { display: flex; gap: 5px; margin-bottom: 10px; }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    .m-input { flex: 1; padding: 8px; border-radius: 8px; border: none; }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                .m-btn-enviar, .m-btn-horario { cursor: pointer; background: var(--m-primary); border: none; padding: 8px; 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             border-radius: 8px; color: #3a2e1f; font-weight: bold; }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     `;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             document.head.appendChild(style);

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     container.querySelector('.m-burbuja').onclick = async () => {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 this.expandido = !this.expandido;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             container.querySelector('.m-ventana').style.display = this.expandido ? 'flex' : 'none';
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         if (this.expandido) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         await Engine.marcarComoLeido();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         await this.cargarMensajes();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             };

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     container.querySelector('.m-btn-enviar').onclick = async () => {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 const input = container.querySelector('.m-input');
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             if (input.value.trim()) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             await Engine.enviarMensaje(input.value);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             input.value = '';
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             await this.cargarMensajes();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 };

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         container.querySelector('.m-btn-horario').onclick = () => {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     alert(Engine.obtenerHorario());
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             };

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     this.detectarColisiones();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             async cargarMensajes() {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     const contenedor = document.querySelector('.m-mensajes');
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             await Engine.recibirMensajes((mensajes) => {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         contenedor.innerHTML = mensajes.map(m => `
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         <div class="${m.leido ? 'm-leido' : 'm-no-leido'}">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             <strong>${m.usuario}:</strong> ${m.texto}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         `).join('');
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         detectarColisiones() {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 const burbuja = document.querySelector('.m-burbuja');
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         setInterval(() => {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     const rectBurbuja = burbuja.getBoundingClientRect();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 const criticos = document.querySelectorAll('.elemento-critico');
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             let colision = false;

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         criticos.forEach(el => {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         const rectEl = el.getBoundingClientRect();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         if (!(rectBurbuja.right < rectEl.left || rectBurbuja.left > rectEl.right || 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               rectBurbuja.bottom < rectEl.top || rectBurbuja.top > rectEl.bottom)) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   colision = true;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               });

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           burbuja.style.transform = colision ? 'translateY(-80px)' : 'translateY(0)';
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   }, 300);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       }